apiVersion: v1
kind: Secret
metadata:
  name: chatbot-secrets
type: Opaque
stringData:
  GEMINI_API_KEY: "xxxxxx"  # Replace with your actual key
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-chatbot
  labels:
    app: ai-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-chatbot
  template:
    metadata:
      labels:
        app: ai-chatbot
    spec:
      containers:
      - name: ai-chatbot
        image: ai-chatbot:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        envFrom:
        - secretRef:
            name: chatbot-secrets
        volumeMounts:
        - name: responses
          mountPath: /app/responses
        - name: temp-responses
          mountPath: /app/temp_responses
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
      volumes:
      - name: responses
        emptyDir: {}
      - name: temp-responses
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: ai-chatbot
spec:
  selector:
    app: ai-chatbot
  ports:
  - port: 80
    targetPort: 5000
  type: ClusterIP